#!/bin/bash
# This script is automatically generated by setup.sh

# Change to the directory where this script is located to ensure all paths are correct
cd "$(dirname "$0")"

echo "🚀 Launching TaskMaster..."

# Run the Electron application using the start script from package.json
npm start
