#!/bin/bash
# setup.sh

echo "🚀 Setting up TaskMaster - One-Time Setup"
echo "==============================================="

# --- 1. PREREQUISITE CHECKS ---
# Check if Python 3 is installed
if ! command -v python3 &> /dev/null; then
    echo "❌ FATAL: Python 3 is not installed. Please install Python 3 and run this script again."
    exit 1
fi
echo "✅ Python 3 found"

# Check if Node.js and npm are installed (both are required for Electron)
if ! command -v node &> /dev/null || ! command -v npm &> /dev/null; then
    echo "❌ FATAL: Node.js and/or npm are not installed. They are required for the desktop app."
    echo "   Please install Node.js (which includes npm) and run this script again."
    exit 1
fi
echo "✅ Node.js and npm found"

# --- 2. PYTHON VIRTUAL ENVIRONMENT ---
echo "📦 Creating Python virtual environment ('task_breakdown_env')..."
python3 -m venv task_breakdown_env

echo "📥 Installing Python packages (Flask, Gemini, etc.)..."
# Activate venv for this script's session to install packages into it
source task_breakdown_env/bin/activate
pip install -q flask google-generativeai python-dotenv # -q for quieter install
deactivate
echo "✅ Python packages installed."

# --- 3. NODE.JS DEPENDENCIES ---
echo "📦 Installing Electron dependencies via npm..."
npm install
echo "✅ Electron dependencies installed."

# --- 4. CREATE THE LAUNCHER SCRIPT ---
echo "⚙️  Creating the 'run.sh' launcher script..."
cat > run.sh << 'EOF'
#!/bin/bash
# This script is automatically generated by setup.sh

# Change to the directory where this script is located to ensure all paths are correct
cd "$(dirname "$0")"

echo "🚀 Launching TaskMaster..."

# Run the Electron application using the start script from package.json
npm start
EOF

# Make the launcher executable
chmod +x run.sh
echo "✅ Launcher script 'run.sh' created."

# --- 5. CREATE THE 'taskmaster' ALIAS ---
# Get the absolute path to the current directory
CURRENT_DIR=$(pwd)
# Define the alias command, quoting the path to handle spaces
ALIAS_LINE="alias taskmaster='\"${CURRENT_DIR}/run.sh\"'"

# Determine the correct shell configuration file
if [ -n "$ZSH_VERSION" ]; then
    SHELL_CONFIG_FILE="$HOME/.zshrc"
else
    SHELL_CONFIG_FILE="$HOME/.bashrc"
fi

echo "🔗 Creating permanent 'taskmaster' alias in ${SHELL_CONFIG_FILE}..."

# Check if alias already exists and update it, otherwise add it
if grep -q "alias taskmaster=" "$SHELL_CONFIG_FILE"; then
    # Use a different separator for sed to avoid issues with slashes in paths
    sed -i.bak "s|alias taskmaster=.*|$ALIAS_LINE|" "$SHELL_CONFIG_FILE"
    echo "✅ Updated existing 'taskmaster' alias."
else
    echo "" >> "$SHELL_CONFIG_FILE"
    echo "# TaskMaster Application Alias" >> "$SHELL_CONFIG_FILE"
    echo "$ALIAS_LINE" >> "$SHELL_CONFIG_FILE"
    echo "✅ Added 'taskmaster' alias."
fi

# --- 6. CREATE .env TEMPLATE ---
if [ ! -f ".env" ]; then
    echo "📝 Creating .env file template..."
    cat > .env << EOF
# Gemini API Configuration - IMPORTANT: REPLACE WITH YOUR KEY
GEMINI_API_KEY=your-api-key-here
EOF
    echo "✅ Created .env file template."
fi

# --- 7. FINAL INSTRUCTIONS ---
echo ""
echo "🎉 Setup complete! You're almost ready."
echo ""
echo "📋 FINAL STEPS:"
echo "1. Get your Gemini API key from: https://aistudio.google.com/app/apikey"
echo "2. Edit the .env file and replace 'your-api-key-here' with your actual API key."
echo "3. ‼️ IMPORTANT: Reload your shell for the alias to work. Run:"
echo "   source ${SHELL_CONFIG_FILE}"
echo "   (Or simply open a new terminal window)."
echo "4. Run the application from ANYWHERE by typing:"
echo "   taskmaster"
echo ""